"""Versioned reporting for the provisional stochastic valuation."""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from .valuation import (
    ValuationInputs,
    ValuationResult,
    probability_value_exceeds_market,
    quantile_rows,
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _distribution_figure(
    values: np.ndarray, observed: float, output: Path, as_of: str
) -> None:
    lower, upper = np.percentile(values, [0.5, 99.5])
    lower = min(float(lower), observed)
    upper = max(float(upper), observed)
    shown = values[(values >= lower) & (values <= upper)]
    median = float(np.median(values))
    p10, p90 = np.percentile(values, [10, 90])

    fig, axis = plt.subplots(figsize=(10.2, 5.6))
    axis.hist(
        shown,
        bins=90,
        density=True,
        color="#D9E4F0",
        edgecolor="white",
        linewidth=0.35,
    )
    axis.axvspan(p10, p90, color="#D4AF37", alpha=0.16, label="P10-P90 model range")
    axis.axvline(median, color="#17365D", linewidth=2.1, label=f"Model median: ${median:,.2f}")
    axis.axvline(
        observed,
        color="#B33A3A",
        linewidth=2.1,
        linestyle="--",
        label=f"Observed B close: ${observed:,.2f}",
    )
    axis.set_title("Barrick provisional stochastic value-per-share distribution")
    axis.set_xlabel("Provisional model value (USD/share)")
    axis.set_ylabel("Density")
    axis.grid(axis="y", alpha=0.2)
    axis.legend(frameon=False)
    fig.text(
        0.01,
        0.01,
        "Research sensitivity only; unresolved corporate, accounting and measure bridges remain. "
        f"Valuation as-of: {as_of}.",
        fontsize=8,
    )
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=220, bbox_inches="tight")
    plt.close(fig)


def _latex_quantile_table(path: Path, rows: list[dict[str, Any]], probability: float, observed: float) -> None:
    lines = [
        "% Generated by barrick_unified. Do not edit manually.",
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Provisional stochastic valuation quantiles (research sensitivity only)}",
        "\\label{tab:provisional-valuation-quantiles}",
        "\\begin{tabular}{rrrr}",
        "\\toprule",
        "Quantile & EV proxy (USD mn) & Equity proxy (USD mn) & Value/share (USD) \\\\",
        "\\midrule",
    ]
    for row in rows:
        lines.append(
            f"P{int(row['quantile_pct']):02d} & "
            f"{row['enterprise_value_proxy_usd_mn']:,.0f} & "
            f"{row['equity_value_proxy_usd_mn']:,.0f} & "
            f"{row['value_per_share_proxy_usd']:,.2f} \\\\"
        )
    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\par\\smallskip",
            f"\\footnotesize Observed B close: USD {observed:,.2f}; "
            f"simulation frequency above observed close: {probability:.1%}. "
            "This is not a target price or investment recommendation.",
            "\\end{table}",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_valuation_outputs(
    inputs: ValuationInputs,
    result: ValuationResult,
    output_dir: Path,
    figure_dir: Path,
    manifest_path: Path,
    config_path: Path,
    project_root: Path,
    run_id: str,
) -> dict[str, Any]:
    """Write aggregate/public artifacts; never copy row-level LSE data."""

    output_dir.mkdir(parents=True, exist_ok=True)
    figure_dir.mkdir(parents=True, exist_ok=True)
    # ``output_dir`` is <output-root>/outputs/valuation/<run-id>.  Artifact
    # paths belong to that chosen output root, which may deliberately differ
    # from the source checkout used for code/config provenance.
    artifact_root = output_dir.parents[2]
    rows = quantile_rows(result)
    probability = probability_value_exceeds_market(
        result, inputs.observed_share_price_usd
    )
    quantile_path = output_dir / "valuation_quantiles.csv"
    _write_csv(
        quantile_path,
        rows,
        [
            "quantile_pct",
            "enterprise_value_proxy_usd_mn",
            "equity_value_proxy_usd_mn",
            "value_per_share_proxy_usd",
        ],
    )

    p50 = rows[4]
    summary = {
        "schema_version": "1.0",
        "status": inputs.status,
        "run_id": run_id,
        "valuation_as_of_utc": inputs.valuation_as_of_utc,
        "observed_market_price": {
            "ticker": "B",
            "price_usd": inputs.observed_share_price_usd,
            "timestamp_utc": inputs.observed_share_price_timestamp_utc,
            "source": inputs.observed_share_price_source,
        },
        "median": p50,
        "probability_model_value_exceeds_observed_price": probability,
        "simulation": {"paths": inputs.n_simulations, "seed": inputs.seed},
        "interpretation": "provisional research sensitivity; not a target price or investment recommendation",
        "unresolved_corporate_inputs": list(inputs.unresolved_corporate_inputs),
    }
    summary_json = output_dir / "valuation_summary.json"
    _write_json(summary_json, summary)
    summary_csv = output_dir / "valuation_summary.csv"
    _write_csv(
        summary_csv,
        [
            {"metric": "observed_share_price_usd", "value": inputs.observed_share_price_usd, "unit": "USD/share"},
            {"metric": "median_value_per_share_proxy_usd", "value": p50["value_per_share_proxy_usd"], "unit": "USD/share"},
            {"metric": "median_enterprise_value_proxy_usd_mn", "value": p50["enterprise_value_proxy_usd_mn"], "unit": "USD millions"},
            {"metric": "median_equity_value_proxy_usd_mn", "value": p50["equity_value_proxy_usd_mn"], "unit": "USD millions"},
            {"metric": "probability_model_value_exceeds_observed", "value": probability, "unit": "fraction"},
        ],
        ["metric", "value", "unit"],
    )

    bridge_rows = []
    for level, label in ((10, "P10"), (50, "P50"), (90, "P90")):
        index = next(i for i, row in enumerate(rows) if row["quantile_pct"] == level)
        bridge_rows.extend(
            [
                {"quantile": label, "bridge_item": "enterprise_value_proxy", "value_usd_mn": rows[index]["enterprise_value_proxy_usd_mn"]},
                {"quantile": label, "bridge_item": "less_debt", "value_usd_mn": -inputs.debt_usd_mn},
                {"quantile": label, "bridge_item": "add_cash", "value_usd_mn": inputs.cash_usd_mn},
                {"quantile": label, "bridge_item": "less_minority_interest", "value_usd_mn": -inputs.minority_interest_usd_mn},
                {"quantile": label, "bridge_item": "add_non_operating_assets", "value_usd_mn": inputs.non_operating_assets_usd_mn},
                {"quantile": label, "bridge_item": "less_other_claims", "value_usd_mn": -inputs.other_claims_usd_mn},
                {"quantile": label, "bridge_item": "equity_value_proxy", "value_usd_mn": rows[index]["equity_value_proxy_usd_mn"]},
            ]
        )
    bridge_path = output_dir / "valuation_bridges.csv"
    _write_csv(bridge_path, bridge_rows, ["quantile", "bridge_item", "value_usd_mn"])

    latex_path = output_dir / "valuation_quantiles.tex"
    _latex_quantile_table(
        latex_path, rows, probability, inputs.observed_share_price_usd
    )
    figure_path = figure_dir / "provisional_value_per_share_distribution.png"
    _distribution_figure(
        result.value_per_share_proxy_usd,
        inputs.observed_share_price_usd,
        figure_path,
        inputs.valuation_as_of_utc,
    )

    artifacts = [summary_json, summary_csv, quantile_path, bridge_path, latex_path, figure_path]
    code_paths = [
        project_root / "src" / "barrick_unified" / "valuation.py",
        project_root / "src" / "barrick_unified" / "valuation_reporting.py",
        project_root / "run_provisional_valuation.py",
    ]
    manifest = {
        "schema_version": "1.0",
        "status": inputs.status,
        "run_id": run_id,
        "valuation_as_of_utc": inputs.valuation_as_of_utc,
        "units": {
            "enterprise_and_equity_value": "USD millions",
            "value_per_share": "USD/share",
            "gold_price": "USD/troy oz",
            "production": "thousand troy oz per quarter",
            "unit_cost": "USD/troy oz",
        },
        "model_boundary": {
            "operations": "Team 4 quarterly production/unit-cost arrays and GBM/NSS/volatility assumptions",
            "cash_flow_and_discounting": "Team 5 growth/ROIC reinvestment identity and mean-reverting WACC, adapted to five years",
            "team8": "architecture reviewed; current GLD/Q surface is not used as gold/P because G1.5, GLD-to-gold and Q-to-P bridges are unresolved",
            "accounting_label": "component_margin_pre_reconciliation and FCFF_proxy; not audited EBITDA/FCFF",
            "terminal_policy": "positive terminal after-tax component margin only; perpetual growth proxy",
        },
        "observed_market_price": summary["observed_market_price"],
        "seed": inputs.seed,
        "simulation_paths": inputs.n_simulations,
        "probability_model_value_exceeds_observed_price": probability,
        "assumptions": list(inputs.assumptions),
        "unresolved_corporate_inputs": list(inputs.unresolved_corporate_inputs),
        "input_config": {
            "path": config_path.relative_to(project_root).as_posix(),
            "sha256": sha256(config_path),
        },
        "reference_files": list(inputs.reference_files),
        "code": [
            {
                "path": path.relative_to(project_root).as_posix(),
                "sha256": sha256(path),
            }
            for path in code_paths
        ],
        "artifacts": [
            {
                "path": path.relative_to(artifact_root).as_posix(),
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
            for path in artifacts
        ],
        "not_investment_advice": True,
    }
    _write_json(manifest_path, manifest)
    return manifest
